"""OntologySkill 生成器 — 将知识文档转化为可执行的 Python 代码.

生成内容包括：
1. 数据类（从 Object 文档）
2. DAO 接口（数据访问层桩）
3. OntologySkill 类（含前置检查、核心逻辑、后置检查、回滚、审计）
4. 测试用例（从边界条件自动生成）
"""

from __future__ import annotations

import textwrap
from typing import Any

from kea.generator.pseudocode_translator import translate_pseudocode
from kea.parser.models import (
    DocType,
    InputParam,
    KnowledgeDocument,
    OutputParam,
    PropertyDef,
)


class SkillGenerator:
    """OntologySkill 代码生成器."""

    INDENT = "    "

    def generate(self, doc: KnowledgeDocument) -> str:
        """生成单个知识文档对应的 OntologySkill Python 代码.

        Args:
            doc: 知识文档（Action 或 Logic）

        Returns:
            Python 代码字符串
        """
        if doc.doc_type == DocType.ACTION:
            return self._generate_action(doc)
        elif doc.doc_type == DocType.LOGIC:
            return self._generate_logic(doc)
        elif doc.doc_type == DocType.OBJECT:
            return self._generate_dataclass(doc)
        else:
            return f"# Rule 文档不生成代码: {doc.name}\n"

    def generate_module(self, docs: list[KnowledgeDocument]) -> str:
        """生成包含多个 OntologySkill 的 Python 模块.

        Args:
            docs: 知识文档列表

        Returns:
            完整的 Python 模块代码
        """
        lines = [
            '# Auto-generated by KEA (Knowledge Extraction Agent)',
            '# Do NOT edit manually — regenerate from knowledge documents',
            '',
            'from __future__ import annotations',
            '',
            'import logging',
            'from dataclasses import dataclass, field',
            'from decimal import Decimal',
            'from typing import Any, Optional',
            '',
            'logger = logging.getLogger(__name__)',
            '',
        ]

        # 先生成所有 Object 的数据类
        for doc in docs:
            if doc.doc_type == DocType.OBJECT:
                lines.append(self._generate_dataclass(doc))
                lines.append("")

        # 再生成 Action/Logic
        for doc in docs:
            if doc.doc_type in (DocType.ACTION, DocType.LOGIC):
                lines.append(self._generate_skill_class(doc))
                lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Object → 数据类
    # ------------------------------------------------------------------

    def _generate_dataclass(self, doc: KnowledgeDocument) -> str:
        """从 Object 文档生成 Python dataclass."""
        class_name = self._to_class_name(doc.english_name or doc.id)

        lines = [
            f"@dataclass",
            f"class {class_name}:",
            f'{self.INDENT}"""{doc.agent_context.one_liner if doc.agent_context else doc.name}"""',
            "",
        ]

        for prop in doc.properties:
            py_type = self._map_property_type(prop.type)
            default = " = None" if not prop.is_primary_key else ""
            comment = f"  # {prop.description}" if prop.description else ""
            lines.append(f"{self.INDENT}{prop.english_name or prop.name}: {py_type}{default}{comment}")

        if not doc.properties:
            lines.append(f"{self.INDENT}pass")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Action → OntologySkill 类
    # ------------------------------------------------------------------

    def _generate_action(self, doc: KnowledgeDocument) -> str:
        """从 Action 文档生成 OntologySkill 类."""
        return self._generate_skill_class(doc)

    def _generate_logic(self, doc: KnowledgeDocument) -> str:
        """从 Logic 文档生成 OntologySkill 编排器类."""
        return self._generate_skill_class(doc)

    def _generate_skill_class(self, doc: KnowledgeDocument) -> str:
        """生成 OntologySkill 类（Action 和 Logic 共用结构）."""
        class_name = self._to_class_name(doc.english_name or doc.id)
        func_name = doc.id.replace("-", "_").replace(".", "_")

        lines = [
            f"class {class_name}Skill:",
            f'{self.INDENT}"""{doc.agent_context.one_liner if doc.agent_context else doc.name}"""',
            "",
            f"{self.INDENT}def __init__(self, registry: Any = None, dao: Any = None) -> None:",
            f"{self.INDENT}{self.INDENT}self.registry = registry",
            f"{self.INDENT}{self.INDENT}self.dao = dao",
            f"{self.INDENT}{self.INDENT}self.audit_log: list[dict] = []",
            "",
        ]

        # 主执行函数
        lines.extend(self._generate_execute_method(doc, func_name))

        # 前置条件检查函数
        if doc.preconditions:
            lines.extend(self._generate_precondition_method(doc, func_name))

        # 后置条件检查函数
        if doc.postconditions:
            lines.extend(self._generate_postcondition_method(doc, func_name))

        # 回滚函数
        if doc.rollback_rules:
            lines.extend(self._generate_rollback_method(doc, func_name))

        # 核心逻辑函数（从伪代码翻译）
        if doc.pseudocode:
            lines.extend(self._generate_core_logic(doc, func_name))

        return "\n".join(lines)

    def _generate_execute_method(self, doc: KnowledgeDocument, func_name: str) -> list[str]:
        """生成主执行函数（含前置检查、核心逻辑调用、后置检查、异常回滚）."""
        # 函数签名
        params_str = self._build_function_params(doc.inputs)
        return_type = self._build_return_type(doc.outputs)

        lines = [
            f"{self.INDENT}def execute(self, {params_str}){return_type}:",
        ]

        # 审计日志开始
        lines.append(f'{self.INDENT}{self.INDENT}self._audit("start", {{"doc_id": "{doc.id}", "inputs": locals()}})')
        lines.append("")

        # 前置条件检查
        if doc.preconditions:
            lines.append(f"{self.INDENT}{self.INDENT}self._check_preconditions({self._build_param_names(doc.inputs)})")
            lines.append("")

        # try-except 包裹核心逻辑
        lines.append(f"{self.INDENT}{self.INDENT}try:")

        # 核心逻辑调用
        core_call = self._build_core_call(doc, func_name)
        if doc.outputs:
            lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}result = {core_call}")
        else:
            lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}{core_call}")

        lines.append("")

        # 后置条件检查
        if doc.postconditions:
            if doc.outputs:
                lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}self._check_postconditions(result)")
            else:
                lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}self._check_postconditions()")
            lines.append("")

        # 审计日志成功
        lines.append(f'{self.INDENT}{self.INDENT}{self.INDENT}self._audit("success", {{"result": result if "result" in dir() else None}})')

        # return
        if doc.outputs:
            lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}return result")

        # except 块
        lines.append(f"{self.INDENT}{self.INDENT}except Exception as e:")

        # 审计日志失败
        lines.append(f'{self.INDENT}{self.INDENT}{self.INDENT}self._audit("failure", {{"error": str(e)}})')

        # 回滚
        if doc.rollback_rules:
            lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}self._rollback({self._build_param_names(doc.inputs)})")

        lines.append(f"{self.INDENT}{self.INDENT}{self.INDENT}raise")

        lines.append("")

        return lines

    def _generate_precondition_method(self, doc: KnowledgeDocument, func_name: str) -> list[str]:
        """生成前置条件检查函数."""
        params_str = self._build_function_params(doc.inputs)

        lines = [
            f"{self.INDENT}def _check_preconditions(self, {params_str}) -> None:",
        ]

        for pre in doc.preconditions:
            # 将自然语言前置条件转化为 assert
            # 简化处理：直接作为注释保留，实际断言在伪代码中
            lines.append(f'{self.INDENT}{self.INDENT}# {pre}')
            # 尝试提取简单断言
            assert_stmt = self._precondition_to_assert(pre)
            if assert_stmt:
                lines.append(f"{self.INDENT}{self.INDENT}{assert_stmt}")

        lines.append("")
        return lines

    def _generate_postcondition_method(self, doc: KnowledgeDocument, func_name: str) -> list[str]:
        """生成后置条件检查函数."""
        result_param = "result: Any"

        lines = [
            f"{self.INDENT}def _check_postconditions(self, {result_param}) -> None:",
        ]

        for post in doc.postconditions:
            lines.append(f'{self.INDENT}{self.INDENT}# {post}')
            assert_stmt = self._postcondition_to_assert(post)
            if assert_stmt:
                lines.append(f"{self.INDENT}{self.INDENT}{assert_stmt}")

        lines.append("")
        return lines

    def _generate_rollback_method(self, doc: KnowledgeDocument, func_name: str) -> list[str]:
        """生成回滚函数."""
        params_str = self._build_function_params(doc.inputs)

        lines = [
            f"{self.INDENT}def _rollback(self, {params_str}) -> None:",
            f'{self.INDENT}{self.INDENT}"""回滚操作."""',
        ]

        # 从 rollback_rules 生成
        for rule in doc.rollback_rules:
            lines.append(f"{self.INDENT}{self.INDENT}# {rule}")

        # 如果有伪代码中的 rollback 函数，也翻译
        rollback_code = self._extract_rollback_pseudocode(doc.pseudocode)
        if rollback_code:
            translated = translate_pseudocode(rollback_code)
            for line in translated.split("\n"):
                if line.strip():
                    lines.append(f"{self.INDENT}{self.INDENT}{line.strip()}")

        lines.append("")
        return lines

    def _generate_core_logic(self, doc: KnowledgeDocument, func_name: str) -> list[str]:
        """生成核心逻辑函数（从伪代码翻译）."""
        translated = translate_pseudocode(doc.pseudocode, doc.id)

        lines = [
            f"{self.INDENT}def _{func_name}(self, {self._build_function_params(doc.inputs)}){self._build_return_type(doc.outputs)}:",
            f'{self.INDENT}{self.INDENT}"""核心业务逻辑."""',
        ]

        for line in translated.split("\n"):
            if line.strip():
                lines.append(f"{self.INDENT}{self.INDENT}{line.strip()}")

        lines.append("")
        return lines

    # ------------------------------------------------------------------
    # 辅助方法
    # ------------------------------------------------------------------

    def _build_function_params(self, inputs: list[InputParam]) -> str:
        """构建函数参数字符串."""
        parts = []
        for inp in inputs:
            py_type = self._map_type(inp.type)
            if inp.required:
                parts.append(f"{inp.name}: {py_type}")
            else:
                parts.append(f"{inp.name}: Optional[{py_type}] = None")
        return ", ".join(parts)

    def _build_param_names(self, inputs: list[InputParam]) -> str:
        """构建参数名字符串."""
        return ", ".join(inp.name for inp in inputs)

    def _build_return_type(self, outputs: list[OutputParam]) -> str:
        """构建返回类型字符串."""
        if not outputs:
            return ""
        if len(outputs) == 1:
            return f" -> {self._map_type(outputs[0].type)}"
        return " -> dict"

    def _build_core_call(self, doc: KnowledgeDocument, func_name: str) -> str:
        """构建核心逻辑调用语句."""
        param_names = self._build_param_names(doc.inputs)
        return f"self._{func_name}({param_names})"

    def _precondition_to_assert(self, pre: str) -> str:
        """尝试将自然语言前置条件转化为 assert 语句."""
        # 简单模式匹配
        # "状态 == '待支付'" → assert 状态 == '待支付', "..."
        if "==" in pre or ">=" in pre or "<=" in pre or ">" in pre or "<" in pre:
            return f'assert {pre}, "前置条件不满足: {pre}"'

        # "必须有 xxx" → assert xxx
        must_match = __import__('re').match(r'必须有\s+(.+)', pre)
        if must_match:
            expr = must_match.group(1)
            return f'assert {expr}, "前置条件不满足: {pre}"'

        return ""

    def _postcondition_to_assert(self, post: str) -> str:
        """尝试将自然语言后置条件转化为 assert 语句."""
        if "==" in post or ">=" in post or "<=" in post:
            return f'assert {post}, "后置条件不满足: {post}"'
        return ""

    def _extract_rollback_pseudocode(self, pseudocode: str) -> str:
        """从伪代码中提取 rollback 函数."""
        if not pseudocode:
            return ""

        # 找到 function rollback 开始的位置
        start_idx = pseudocode.find("function rollback")
        if start_idx == -1:
            return ""

        # 提取到下一个 function 定义之前，或到代码块结束
        remaining = pseudocode[start_idx:]
        next_func = remaining.find("\nfunction ", len("function rollback"))
        if next_func != -1:
            return remaining[:next_func].strip()

        return remaining.strip()

    def _to_class_name(self, name: str) -> str:
        """将 snake_case 或中文名转为 PascalCase 类名."""
        if not name:
            return "Unknown"
        # 如果已经是 PascalCase，直接返回
        if name[0].isupper() and "_" not in name and "-" not in name:
            return name
        # 下划线转驼峰
        parts = name.replace("-", "_").split("_")
        return "".join(p.capitalize() for p in parts if p)

    def _map_type(self, type_str: str | None) -> str:
        """类型映射."""
        if not type_str:
            return "Any"
        type_map = {
            "string": "str", "字符串": "str",
            "int": "int", "integer": "int", "整数": "int",
            "float": "float", "number": "float", "数值": "float", "金额": "Decimal",
            "bool": "bool", "boolean": "bool", "布尔": "bool",
            "array": "list", "列表": "list",
            "object": "dict", "对象": "dict",
        }
        return type_map.get(type_str.strip().lower(), type_str)

    def _map_property_type(self, type_str: str) -> str:
        """对象属性类型映射（带 Optional）."""
        base = self._map_type(type_str)
        if base == "str":
            return "str"
        return f"Optional[{base}]"
